[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "same-origin"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
